name: CI - Centro Psicologico Mente Sana 
on: 
  push: 
    branches: [ main ] 
  pull_request: 
    branches: [ main ] 
jobs: 
  verificar: 
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4 
      - name: Verificar ejecucion 
        run: echo "Pipeline ejecutado correctamente" 
